// Package router provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package router

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8yTz24TMRDG32XguOoGuO0tB4QiDo3EEUXIbCaJq13b2F5EVO3BuwKBCqpEiyhcKHBI",
	"+FfgiiL1YaYhufUVkJ2uqgoUcezJ1ni+z/P9vLsNqcyVFCisgWQbTDrCnIVtV8sBz9BvlZYKteUYDgTL",
	"Q9WOFUICxmouhlBGYDAb3OPCatkv0n+1lBFofFBwjX1I7q6M/pL1okYm729haqH0Oi4G0jv20aSaK8ul",
	"gASW04OTXzuL/Sm5o3a3AxFYbv3McPMRy1Xm7R+iNqvuaxutjZYfVCoUTHFI4EYoRaCYHYVwsTqPPUTr",
	"F5+d+Qs7fUjgFtp2YUdSN3x8JqOkMCs611stv6RSWBRBz5TKeBoc4i3jJ2k4+91VjQNI4Ep8/hDx2SvE",
	"zRWBwMXkm7cDTlPkOdNjSGAxceSOqH5N9TeqX1H1keoZ1V9+14/nhz+perk83if3pt3tnM6eLj//IDeh",
	"qprvfiK3S26P3JTcc190L6jaOZ09C/4Njthgqlc41lO5E/ouJZvF5GD+/cn/QwptX6l+R9UHqg9PZm/n",
	"e++93B2vwxaBZUPjv+9NkY27GnNe5NALc56dNP/QhY6yV/4JAAD//6nQJl6OAwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

