// Package router provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package router

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8yTz2sTQRTH/5enx6Ub9ba3HESChwY8SpBx85JM2Z0ZZ2bFUPYwuyhKlYKtWL1Y9ZD4",
	"q+pVAv1jXmNy678gM+lSihI89jSPt+/73vt+HrsNqcyVFCisgWQbTDrCnIWwq+WAZ+hDpaVCbTmGD4Ll",
	"IWvHCiEBYzUXQygjMJgN7nFhtewX6b9Kygg0Pii4xj4kd1eN/pL1okYm729haqH0Oi4G0nfso0k1V5ZL",
	"AQkspwcnv3YW+1NyR+1uByKw3Pqd4eYjlqvMt3+I2qyqr220Nlp+UalQMMUhgRshFYFidhTMxerc9hCt",
	"f7x35gd2+pDALbTtwo6kbvh4T0ZJYVZ0rrda/kmlsCiCnimV8TR0iLeM36Th7KOrGgeQwJX4/BDx2RXi",
	"ZkQgcNH55u2A0xR5zvQYElhMHLkjql9T/Y3qV1R9pHpG9Zff9eP54U+qXi6P98m9aXc7p7Ony88/yE2o",
	"qua7n8jtktsjNyX33CfdC6p2TmfPPEw2NP5QmyIbdzXmvMih58c2lGKDqV5RWg/rTqi7lMgWk4P59yf/",
	"zy6UfaX6HVUfqD48mb2d7733cne8jmZY6Axo8w9dAFv2yj8BAAD//6W1rECOAwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

