// Package router provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package router

// Profile defines model for Profile.
type Profile struct {
	Name          string `json:"name"`
	SelfIntroduce string `json:"self_introduce"`
}

